name: sovereign
services:
  solana-validator:
    build:
      context: .
      dockerfile: Dockerfile.solana
    ports:
      - "8899:8899"
      - "8900:8900"
    volumes:
      - solana-data:/workspace/ledger
    networks:
      - sovereign-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sovereign-network

  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
      - keydb-data:/data
    networks:
      - sovereign-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5500:5500" # hub
      - "5600:3000" # api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app
      - REDIS_URL=redis://keydb:6379
      - SOLANA_RPC_URL=http://solana-validator:8899
    depends_on:
      - postgres
      - keydb
      - solana-validator
    networks:
      - sovereign-network

networks:
  sovereign-network:
    driver: bridge

volumes:
  solana-data:
  postgres-data:
  keydb-data: